import assert from 'node:assert/strict';
import { cardQuantity, cardsInFolder, extraCards, extraFolder, folderColor, moveCard, posterCount, posterTitle } from '../folder-state.mjs';

const cards=[{id:'a',folderId:null},{id:'b',folderId:'favorites'}];
assert.deepEqual(cardsInFolder(cards,null).map(card=>card.id),['a']);
assert.deepEqual(cardsInFolder(cards,'favorites').map(card=>card.id),['b']);
assert.equal(moveCard(cards,'a','favorites')[0].folderId,'favorites');
assert.equal(moveCard(cards,'b','')[1].folderId,null);
assert.deepEqual(moveCard([{id:'c',title:'',folderId:null}],'c',{id:'favorites',name:'Favorites',autoName:true})[0],{id:'c',title:'Favorites',folderId:'favorites'});
assert.deepEqual(Array.from({length:8},(_,index)=>folderColor(index)),[0,1,2,3,4,5,6,0]);
assert.equal(posterTitle('',{name:'Favorites',autoName:true}),'Favorites');
assert.equal(posterTitle('',{name:'Favorites',autoName:false}),'');
assert.equal(cardQuantity(3),3);
assert.equal(cardQuantity(0),1);
assert.equal(cardQuantity('lots'),1);
assert.equal(cardQuantity(1000),999);
assert.equal(posterCount([{quantity:2},{quantity:3},{}]),6);
assert.equal(extraFolder([{name:'Favorites'},{id:'extra',name:' EXTRA '}]).id,'extra');
assert.deepEqual(extraCards([{id:'a',folderId:'main',quantity:3},{id:'b',folderId:'extra',quantity:2},{id:'c',folderId:'main',quantity:1}],'extra'),[{id:'a',folderId:'main',quantity:2,extraCopy:true}]);
console.log('folder-state checks passed');
